version: '3.7'

services:
  database:
    container_name: database
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - network-api
    volumes:
      - ./dados:/var/lib/postgresql/data
  
  api:
    container_name: biblioteca_api
    image: biblioteca_api
    build: .
    command: bash -c "rails db:setup && rails server -b '0.0.0.0'"
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - network-api

networks:
  network-api:
    external:
      name: network-api