name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./aplicacao
      run: docker-composer up -d

  test:

    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        working-directory: ./aplicacao
        run: docker-compose run api bash -c "rails db:reset; rspec"
      
  lint:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        working-directory: ./aplicacao
        run: docker-compose run api bash -c "gem install rubocop; rubocop -A --fail-level F"
